### ISSUE TITLE
  java.lang.RuntimeException: format changed twice

### ISSUE THREAD

**Issue by CrezyProgrammer** [israel-fl/bitmap2video#14]
java.lang.RuntimeException: format changed twice
        at com.homesoft.encoder.FrameBuilder.drainCodec(FrameBuilder.kt:170)
        at com.homesoft.encoder.FrameBuilder.postCanvasFrame(FrameBuilder.kt:134)
        at com.homesoft.encoder.FrameBuilder.drawBitmapAndPostCanvas(FrameBuilder.kt:125)
        at com.homesoft.encoder.FrameBuilder.createFrame(FrameBuilder.kt:102)
        at com.homesoft.encoder.Muxer.mux(Muxer.kt:75)
        at com.homesoft.encoder.Muxer.muxAsync(Muxer.kt:93)
        at com.homesoft.bitmap2video.MainActivity$createVideoAsync$1.invokeSuspend(MainActivity.kt:142)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by abdulmic** [comment]
I am leaving here the solution so anyone who stumbles get a fix.
the function createVideo(muxer) is called two times in MainAcitivity.java file comment one of them and boom crash gone
![image](https://github.com/israel-fl/bitmap2video/assets/134485592/aa3392f4-04ca-4f8a-a96e-3656ff914de1)
